export const storesActionTypes = {
    SET_STORES : 'SET_STORES',
    SET_CITY_STORES : 'SET_CITY_STORES',
    SET_LONGITUDE : 'SET_LONGITUDE',
    SET_LATITUDE : 'SET_LATITUDE',
    SET_FIXTURES : 'SET_FIXTURES',
    SET_ACTIVE_PAGE : 'SET_ACTIVE_PAGE',
    SET_ACTIVE_LOCATION : 'SET_ACTIVE_LOCATION',
}